const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
let year=117, scale=.86, x=0, y=0, dragging=false, sx=0, sy=0;
const map=$('#map'), viewport=$('#mapViewport'), card=$('#mapCard');
const clampPan=()=>{const mx=Math.max(0,viewport.clientWidth*(scale-1)/2),my=Math.max(0,viewport.clientHeight*(scale-1)/2);x=Math.max(-mx,Math.min(mx,x));y=Math.max(-my,Math.min(my,y))};
const setTransform=()=>{clampPan();map.style.transform=`translate(${x}px,${y}px) scale(${scale})`;viewport.classList.toggle('can-pan',scale>1)};
$('#prevYear').onclick=()=>$('#year').textContent=--year;
$('#nextYear').onclick=()=>$('#year').textContent=++year;
$('#zoomIn').onclick=()=>{scale=Math.min(3,scale+.25);setTransform()};
$('#zoomOut').onclick=()=>{scale=Math.max(.75,scale-.25);if(scale<=1)x=y=0;setTransform()};
$('#zoomReset').onclick=()=>{scale=.86;x=y=0;setTransform()};
viewport.addEventListener('wheel',e=>{e.preventDefault();scale=Math.max(.75,Math.min(3,scale+(e.deltaY<0?.18:-.18)));if(scale<=1)x=y=0;setTransform()},{passive:false});
viewport.addEventListener('dblclick',e=>{if(e.target.closest('button'))return;scale=Math.min(3,scale+.4);setTransform()});
viewport.onpointerdown=e=>{if(e.target.closest('button'))return;if(scale<=1){scale=1.15;setTransform()}dragging=true;sx=e.clientX-x;sy=e.clientY-y;viewport.classList.add('dragging');viewport.setPointerCapture(e.pointerId)};
viewport.onpointermove=e=>{if(!dragging)return;x=e.clientX-sx;y=e.clientY-sy;setTransform()};
viewport.onpointerup=viewport.onpointercancel=()=>{dragging=false;viewport.classList.remove('dragging')};
setTransform();
const layerOverlay=$('#layerOverlay');
const provinceStats=[
  {n:'Британия',x:27,y:24,p:'2,1 млн',e:'+1 180 ₯',t:'Олово'}, {n:'Галлия',x:31,y:41,p:'7,4 млн',e:'+4 620 ₯',t:'Вино'},
  {n:'Испания',x:19,y:57,p:'5,2 млн',e:'+3 280 ₯',t:'Серебро'}, {n:'Италия',x:43,y:57,p:'7,0 млн',e:'+8 940 ₯',t:'Ремесло'},
  {n:'Паннония',x:56,y:47,p:'1,7 млн',e:'+960 ₯',t:'Железо'}, {n:'Дакия',x:62,y:41,p:'1,0 млн',e:'+2 440 ₯',t:'Золото'},
  {n:'Ахайя',x:61,y:67,p:'2,3 млн',e:'+1 720 ₯',t:'Мрамор'}, {n:'Азия',x:71,y:65,p:'6,0 млн',e:'+5 380 ₯',t:'Шёлк'},
  {n:'Сирия',x:84,y:69,p:'4,7 млн',e:'+4 110 ₯',t:'Пряности'}, {n:'Египет',x:73,y:86,p:'5,5 млн',e:'+6 750 ₯',t:'Зерно'},
  {n:'Африка',x:38,y:75,p:'3,4 млн',e:'+3 960 ₯',t:'Масло'}
];
const renderLayer=layer=>{map.className='map layer-'+layer;layerOverlay.innerHTML='';if(layer==='population')layerOverlay.innerHTML=provinceStats.map(s=>`<button class="data-marker population-marker" style="left:${s.x}%;top:${s.y}%"><small>${s.n}</small><b>♟ ${s.p}</b></button>`).join('');if(layer==='economy')layerOverlay.innerHTML=provinceStats.map(s=>`<button class="data-marker economy-marker" style="left:${s.x}%;top:${s.y}%"><small>${s.n}</small><b>${s.e}</b></button>`).join('');if(layer==='trade')layerOverlay.innerHTML=provinceStats.filter((_,i)=>[2,3,6,7,8,9,10].includes(i)).map(s=>`<button class="data-marker trade-marker" style="left:${s.x}%;top:${s.y}%"><small>${s.n}</small><b>⚖ ${s.t}</b></button>`).join('')};
const activateLayer=layer=>{$$('#layers button').forEach(b=>b.classList.toggle('active',b.dataset.layer===layer));renderLayer(layer)};
$$('#layers button').forEach(btn=>btn.onclick=()=>activateLayer(btn.dataset.layer));activateLayer('political');
$('#legendToggle').onclick=()=>$('#legend').classList.toggle('hidden');
const places={rome:['ROMA','Италия · столица империи','Население: 1 000 000','Порядок: 92%'],athens:['ATHENAE','Провинция Ахайя','Население: 150 000','Культура: процветает'],alexandria:['ALEXANDRIA','Египет · имперский мегаполис','Население: 500 000','Флот: 36 кораблей'],antioch:['ANTIOCHIA','Сирия · восточная столица','Население: 400 000','Гарнизон: 8 400'],tarraco:['TARRACO','Тарраконская Испания','Доход: 3 280 ₯','Порядок: 86%'],syracuse:['SYRACVSAE','Сицилия · великий порт','Население: 120 000','Флот: 24 корабля'],carthage:['CARTHAGO','Африка Проконсульская','Население: 300 000','Поставки зерна: 91%']};
const provinceData={
britannia:['БРИТАНИЯ','Лондиний','2,1 млн','74%','олово, шерсть'],belgica:['БЕЛГИКА','Дурокортор','2,4 млн','76%','зерно, железо'],lugdunensis:['ЛУГДУНСКАЯ ГАЛЛИЯ','Лугдунум','2,8 млн','82%','вино, керамика'],aquitania:['АКВИТАНИЯ','Медиолан Сантонов','2,1 млн','80%','вино, соль'],narbonensis:['НАРБОНСКАЯ ГАЛЛИЯ','Нарбон','1,9 млн','86%','вино, масло'],germania_inferior:['НИЖНЯЯ ГЕРМАНИЯ','Колония Агриппина','1,0 млн','72%','лес, железо'],germania_superior:['ВЕРХНЯЯ ГЕРМАНИЯ','Могонтиак','0,9 млн','69%','оружие, лес'],raetia:['РЕЦИЯ','Августа Винделиков','0,7 млн','78%','скот, железо'],noricum:['НОРИК','Вирун','0,6 млн','81%','железо, соль'],pannonia_superior:['ВЕРХНЯЯ ПАННОНИЯ','Карнунт','0,9 млн','74%','скот, железо'],pannonia_inferior:['НИЖНЯЯ ПАННОНИЯ','Аквинк','0,8 млн','72%','зерно, лошади'],dacia:['ДАКИЯ','Ульпия Траяна','1,0 млн','66%','золото, соль'],dalmatia:['ДАЛМАЦИЯ','Салона','1,2 млн','79%','лес, камень'],moesia_superior:['ВЕРХНЯЯ МЁЗИЯ','Виминаций','0,8 млн','70%','руда, скот'],moesia_inferior:['НИЖНЯЯ МЁЗИЯ','Томы','0,9 млн','71%','зерно, рыба'],thracia:['ФРАКИЯ','Перінф','1,4 млн','75%','зерно, вино'],macedonia:['МАКЕДОНИЯ','Фессалоники','1,6 млн','83%','лес, серебро'],epirus:['ЭПИР','Никополь','0,5 млн','84%','скот, масло'],achaia:['АХАЙЯ','Коринф','2,3 млн','88%','мрамор, масло'],italia:['ИТАЛИЯ','Рим','7,0 млн','92%','ремесло, вино'],lusitania:['ЛУЗИТАНИЯ','Августа Эмерита','1,1 млн','83%','золото, шерсть'],baetica:['БЕТИКА','Кордуба','1,7 млн','89%','масло, гарум'],tarraconensis:['ТАРРАКОНСКАЯ ИСПАНИЯ','Тарракон','2,4 млн','84%','серебро, вино'],mauretania_tingitana:['МАВРЕТАНИЯ ТИНГИТАНСКАЯ','Тингис','0,6 млн','69%','пурпур, рыба'],mauretania_caesariensis:['МАВРЕТАНИЯ ЦЕЗАРЕЙСКАЯ','Кесария','1,0 млн','72%','лошади, зерно'],africa:['АФРИКА ПРОКОНСУЛЬСКАЯ','Карфаген','3,4 млн','84%','зерно, масло'],sicilia:['СИЦИЛИЯ','Сиракузы','1,1 млн','87%','зерно, вино'],sardinia:['КОРСИКА И САРДИНИЯ','Каралис','0,5 млн','78%','зерно, металлы'],cyrenaica:['КРИТ И КИРЕНАИКА','Кирена','0,8 млн','77%','сильфий, зерно'],creta:['КРИТ','Гортина','0,4 млн','82%','вино, масло'],bithynia:['ВИФИНИЯ И ПОНТ','Никомедия','2,0 млн','80%','лес, зерно'],asia:['АЗИЯ','Эфес','6,0 млн','85%','шёлк, зерно'],galatia:['ГАЛАТИЯ','Анкира','1,4 млн','76%','шерсть, зерно'],lycia:['ЛИКИЯ И ПАМФИЛИЯ','Перга','1,0 млн','82%','дерево, вино'],cilicia:['КИЛИКИЯ','Тарс','1,2 млн','74%','лён, лес'],cappadocia:['КАППАДОКИЯ','Кесария','1,5 млн','73%','лошади, металлы'],syria:['СИРИЯ','Антиохия','4,7 млн','68%','стекло, пряности'],mesopotamia:['МЕСОПОТАМИЯ','Нисибис','1,3 млн','61%','зерно, ткани'],iudaea:['ИУДЕЯ','Кесария Приморская','1,5 млн','64%','масло, финики'],arabia:['АРАВИЯ ПЕТРЕЙСКАЯ','Бостра','0,7 млн','70%','ладан, пряности'],aegyptus:['ЕГИПЕТ','Александрия','5,5 млн','81%','зерно, папирус'],cyprus:['КИПР','Саламин','0,4 млн','85%','медь, вино']};
$$('.province').forEach(p=>{p.setAttribute('tabindex','0');p.setAttribute('role','button');p.setAttribute('aria-label','Провинция '+provinceData[p.dataset.province][0]);const select=e=>{e.stopPropagation();$$('.province').forEach(x=>x.classList.remove('selected'));p.classList.add('selected');const d=provinceData[p.dataset.province],box=p.getBBox(),kx=map.clientWidth/1280,ky=map.clientHeight/940;card.innerHTML=`<small>ПРОВИНЦИЯ</small><h3>${d[0]}</h3><p><b>Столица:</b> ${d[1]}</p><p>Население: ${d[2]}</p><p>Порядок: ${d[3]}</p><p>Товары: ${d[4]}</p>`;card.style.left=Math.max(8,Math.min(map.clientWidth-245,(box.x+box.width+12)*kx))+'px';card.style.top=Math.max(8,Math.min(map.clientHeight-170,(box.y+box.height/2-80)*ky))+'px';card.classList.add('show')};p.addEventListener('click',select);p.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')select(e)})});
$$('.city').forEach(b=>b.onclick=e=>{e.stopPropagation();const d=places[b.dataset.place],r=b.getBoundingClientRect(),v=viewport.getBoundingClientRect();card.innerHTML=`<h3>${d[0]}</h3><p>${d[1]}</p><p>${d[2]}</p><p>${d[3]}</p>`;card.style.left=Math.min(v.width-250,r.left-v.left+20)/scale+'px';card.style.top=Math.max(10,(r.top-v.top-50)/scale)+'px';card.classList.add('show')});
$$('.legion').forEach(b=>b.onclick=e=>{e.stopPropagation();card.innerHTML=`<h3>LEGIO ${b.dataset.legion}</h3><p><b>Командующий:</b> ${b.dataset.commander}</p><p><b>Рубеж:</b> ${b.title}</p><p>Численность: ${4800+Math.round(Math.random()*500)}</p><p>Мораль: 88% · Снабжение: 76%</p><p>Статус: готов к приказу</p>`;card.style.left=(b.offsetLeft+25)+'px';card.style.top=(b.offsetTop-65)+'px';card.classList.add('show')});
viewport.onclick=e=>{if(!e.target.closest('.city,.legion,.province')){card.classList.remove('show');$$('.province').forEach(x=>x.classList.remove('selected'))}};
const input=$('#advisorText');input.oninput=()=>$('#count').textContent=input.value.length;
const chatKey='imperium-advisor-chat-v1',messages=$('#messages');
const saveChat=()=>localStorage.setItem(chatKey,messages.innerHTML);
const savedChat=localStorage.getItem(chatKey);if(savedChat)messages.innerHTML=savedChat;
const scrollChat=()=>requestAnimationFrame(()=>{messages.scrollTop=messages.scrollHeight;requestAnimationFrame(()=>messages.scrollTop=messages.scrollHeight)});
const answer=q=>{const t=q.toLowerCase();if(t.includes('торгов'))return 'Рекомендую усилить маршрут Александрия — Остия. Снижение портовой пошлины на один пункт даст рост оборота, но временно уменьшит доход казны.';if(t.includes('легион')||t.includes('границ'))return 'Предлагаю перебросить Legio XIII Gemina к Антиохии и усилить разведку. Это займёт 18 дней и потребует 640 мер провианта.';if(t.includes('налог'))return 'Повышение налога сейчас принесёт быстрый доход, но снизит порядок в восточных провинциях. Безопаснее расширить сбор торговых пошлин.';return 'Я изучил донесение. Сначала следует собрать сведения наместников, затем выбрать ограниченную меру с обратимыми последствиями. Сохранение стабильности остаётся главным приоритетом.'};
function send(text){if(!text.trim())return;messages.insertAdjacentHTML('beforeend',`<div class="message user-msg"><small>ИМПЕРАТОР · СЕЙЧАС</small><p>${text.replace(/[<>]/g,'')}</p></div>`);saveChat();scrollChat();input.focus();setTimeout(()=>{messages.insertAdjacentHTML('beforeend',`<div class="message advisor-msg"><small>СОВЕТНИК · СЕЙЧАС</small><p>${answer(text)}</p><div class="brief"><b>РЕКОМЕНДАЦИЯ</b><p>Подготовить указ и оценить последствия перед подтверждением.</p></div></div>`);saveChat();scrollChat();input.focus()},450)}
$('#advisorForm').onsubmit=e=>{e.preventDefault();send(input.value);input.value='';input.oninput()};$$('.suggestions button').forEach(b=>b.onclick=()=>send(b.textContent));
input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#advisorForm').requestSubmit()}});scrollChat();
const sectionData={Легионы:[['28','боеспособных легионов'],['82%','средняя мораль'],['76%','снабжение']],Провинции:[['42','провинции'],['78%','средний порядок'],['3','требуют внимания']],Экономика:[['84 720 ₯','казна'],['+1 240 ₯','месячный баланс'],['12%','торговый рост']],Торговля:[['17','активных маршрутов'],['94%','безопасность путей'],['8 430 ₯','доход']],Строительство:[['6','проектов'],['2','акведука'],['14 мес.','до завершения']],Дипломатия:[['7','союзников'],['2','напряжённых рубежа'],['61%','влияние']],Разведка:[['34','агента'],['3','новых донесения'],['Средний','уровень угрозы']],Карта:[['117','текущий год'],['42','провинции'],['Pax Romana','состояние']]};
$$('#bottomNav button').forEach(b=>b.onclick=()=>{$$('#bottomNav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const direct={Карта:'political',Легионы:'military',Экономика:'economy',Торговля:'trade'}[b.dataset.section];if(direct){activateLayer(direct);return}const d=sectionData[b.dataset.section];$('#dialogTitle').textContent=b.dataset.section.toUpperCase();$('#dialogContent').innerHTML=`<div class="summary-grid">${d.map(x=>`<div><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</div><p>Подробный реестр подготовлен канцелярией. Выберите объект на карте или обратитесь к советнику для анализа.</p>`;$('#sectionDialog').showModal()});
$('.close').onclick=()=>$('#sectionDialog').close();
